apps/dashboard/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index-list'),
    path('customer/list', CustomerListView.as_view(), name='customer-list'),
    path('customer/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customer_detail'),
    path('<int:pk>/update/', CustomerUpdateView.as_view(), name='customer_update'),
    path('<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete'),


    path('employee/list/', EmployeeListView.as_view(), name='employee_list'),
    path('employee/create/', EmployeeCreateView.as_view(), name='employee_create'),
    path('employee/<int:pk>/', EmployeeDetailView.as_view(), name='employee-detail'),
    path('employee/<int:pk>/update/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('employee/<int:pk>/delete/', EmployeeDeleteView.as_view(), name='employee_delete'),

    path('order/list/', OrderListView.as_view(), name='order_list'),
    path('order/create/', OrderCreateView.as_view(), name='order_create'),
    path('order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('order/<int:pk>/update/', OrderUpdateView.as_view(), name='order_update'),
    path('order/<int:pk>/delete/', OrderDeleteView.as_view(), name='order_delete'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.dashboard.views import *





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.dashboard.urls')),
]

apps/dashboard/models.py
from django.db import models
from apps.markets.models import Location, Product
from django.urls import reverse_lazy
from django.shortcuts import redirect


class Customer(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')])
    location = models.ForeignKey(Location, on_delete=models.CASCADE)


    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse_lazy('customer_detail', args=[str(self.id)])



class Employee(models.Model):
    name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    gender = models.CharField(max_length=1, choices=[('M', 'Male'), ('F', 'Female')])
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

    def get_absolute_url(self):
        return reverse_lazy('employee-detail', args=[str(self.id)])




class Order(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    date = models.DateField()
    total = models.DecimalField(max_digits=8, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return f"{self.product} - {self.date}"
    

    def get_absolute_url(self):
        return reverse_lazy('order-detail', args=[str(self.id)])
    

apps/markets/models.py
from django.db import models

class Location(models.Model):
    country = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    district = models.CharField(max_length=255)

    def __str__(self):
        return self.country


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return self.name

apps/dashboard/forms.py
from django import forms
from .models import Customer, Employee, Order

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('name', 'age', 'gender', 'location')


    
class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ('name', 'age', 'gender', 'location')



class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('product', 'employee', 'customer', 'date')
        

apps/dashboard/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Customer, Order, Employee
from apps.markets.models import Product
from django.db.models import Sum
from django.shortcuts import render


def index(request):
    return render(request,'base.html')


class CustomerListView(ListView):
    model = Customer
    template_name = 'customer/list.html'

class CustomerDetailView(DetailView):
    model = Customer
    template_name = 'customer/customer_detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        customer = self.object
        orders = Order.objects.filter(customer=customer)
        total = orders.aggregate(Sum('product__price'))
        context['orders'] = orders
        context['total'] = total['product__price__sum']
        return context
    



class CustomerCreateView(CreateView):
    template_name = 'customer/customer_create.html'
    model = Customer
    fields = ['name', 'age', 'gender', 'location']
    success_url = reverse_lazy('customer-list')

class CustomerUpdateView(UpdateView):
    template_name = 'customer/customer_update.html'
    model = Customer
    fields = ['name', 'age', 'gender', 'location']

class CustomerDeleteView(DeleteView):
    template_name = 'customer/customer_delete.html'
    model = Customer
    success_url = reverse_lazy('customer-list')



# CRUD for Employee

class EmployeeListView(ListView):
    model = Employee
    template_name = 'Employee/employee_list.html'


class EmployeeDetailView(DetailView):
    model = Employee
    template_name = 'Employee/employee_detail.html'
    slug_field = 'id'
    slug_url_kwarg = 'id'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        employee = self.object
        orders = Order.objects.filter(employee=employee)
        total = orders.aggregate(Sum('product__price'))
        context['orders'] = orders
        context['total'] = total['product__price__sum']
        return context


class EmployeeCreateView(CreateView):
    template_name = 'Employee/employee_create.html'
    model = Employee
    fields = ['name', 'age', 'gender', 'location']
    success_url = reverse_lazy('employee_list')


class EmployeeUpdateView(UpdateView):
    template_name = 'Emploee/employee_update.html'
    model = Employee
    fields = ['name', 'age', 'gender', 'location']

class EmployeeDeleteView(DeleteView):
    template_name = 'Employee/employee_delete.html'
    model = Employee
    success_url = reverse_lazy('employee_list')



# CRUD for Order


class OrderListView(ListView):
    model = Order
    template_name = 'Order/orderlist.html'

class OrderCreateView(CreateView):
    template_name = 'Order/ordercreate.html'
    model = Order
    fields = ['product', 'employee', 'customer', 'date']
    success_url = reverse_lazy('order_list')

class OrderDetailView(DetailView):
    template_name = 'Order/orderdetail.html'
    model = Order

class OrderUpdateView(UpdateView):
    template_name = 'Order/orderupdate.html'
    model = Order
    fields =  ['product', 'employee', 'customer', 'date']
    success_url = reverse_lazy('order_list')

class OrderDeleteView(DeleteView):
    model = Order
    template_name = 'Order/orderdelete.html'
    success_url = reverse_lazy('order_list')

apps/dashboard/templates/Employee/employee_create.html
{% block content %}
  <div class="container">
    <h2 class="text-center mb-4">Create a new employee</h2>
    <form method="post" class="col-md-6 mx-auto">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>

  <style>
    
  form {
    border: 1px solid #11b76d;
    padding: 10px;
    border-radius: 5px;
    margin-top: 20px;
  }
  
  form button {
    margin-top: 20px;
  }
  
  form label {
    display: block;
    margin-bottom: 5px;
  }
  
  form input,
  form select {
    width: 100%;
    padding: 5px;
    border-radius: 3px;
    border: 1px solid #1599c9;
    box-sizing: border-box;
    margin-bottom: 10px;
  }
  
  form input[type="checkbox"] {
    display: inline-block;
    margin-right: 10px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  .form-group label {
    font-weight: bold;
  }</style>
{% endblock %}

apps/dashboard/templates/Employee/employee_delete.html
{% block content %}
  <div class="customer-delete">
    <h2 class="customer-delete__title">Delete customer "{{ employee.name }}"</h2>
    <p class="customer-delete__message">Are you sure you want to delete this employee?</p>
    <form class="customer-delete__form" method="post">
      {% csrf_token %}
      <button class="customer-delete__button" type="submit">Delete</button>
      <a class="customer-delete__cancel-link" href="{% url 'employee_list' %}">Cancel</a>
    </form>
  </div>
  <style>
  .customer-delete {
  margin-top: 30px;
  padding: 20px;
  border: 1px solid #80cd5c;
  border-radius: 5px;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
}

.customer-delete__title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 10px;
}

.customer-delete__message {
  font-size: 16px;
  margin-bottom: 20px;
}

.customer-delete__form {
  display: flex;
  justify-content: flex-end;
  align-items: center;
}

.customer-delete__button {
  background-color: #f44336;
  color: #fff;
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
  margin-right: 10px;
}

.customer-delete__cancel-link {
  color: #f44336;
  text-decoration: none;
  font-size: 16px;
}
  </style>
{% endblock %}

apps/dashboard/templates/Employee/employee_detail.html
<!DOCTYPE html>
<html>
<head>
  <title>{{ object.name }}'s details</title>
  <style>
    body {
      font-family: Arial, sans-serif;
      font-size: 16px;
      line-height: 1.5;
    }

    h1, h2 {
      margin-bottom: 20px;
    }

    table {
      border-collapse: collapse;
      width: 100%;
      margin-bottom: 20px;
    }

    th, td {
      border: 1px solid #ccc;
      padding: 10px;
      text-align: left;
    }

    th {
      background-color: #96f785;
      font-weight: bold;
    }

    tfoot td {
      text-align: right;
    }

    p {
      margin-bottom: 20px;
    }

    .error {
      color: red;
    }
  </style>
</head>
<body>
  <h1>{{ object.name }}'s details</h1>
  <h2>Orders:</h2>
  {% if orders %}
  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Date</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for order in orders %}
      <tr>
        <td>{{ order.product }}</td>
        <td>{{ order.date }}</td>
        <td>${{ order.product.price }}</td>
      </tr>
      {% endfor %}
    </tbody>
    <tfoot>
      <tr>
        <td colspan="2"><strong>Total:</strong></td>
        <td>${{ total }}</td>
      </tr>
    </tfoot>
  </table>
  {% else %}
  <p class="error">No orders found.</p>
  {% endif %}
</body>
</html>

apps/dashboard/templates/Employee/employee_list.html
{% block content %}
  <div class="container">
    <h1 class="text-center">Employee</h1>
    <ul class="employee-list">
      {% for employee in employee_list %}
        <li><a href="{{ employee.get_absolute_url }}">{{ employee.name }}</a></li>
      {% endfor %}
    </ul>
    <a href="{% url 'employee_create' %}" class="add-employee-btn">Добавить работника</a>
  </div>

<style>
  .container {
    max-width: 800px;
    margin: 0 auto;
    padding: 20px;
  }
  
  .employee-list {
    list-style: none;
    padding: 0;
  }
  
  .employee-list li {
    margin-bottom: 10px;
  }
  
  .add-employee-btn {
    display: inline-block;
    margin-top: 20px;
    padding: 10px 20px;
    background-color: #007bff;
    color: #fff;
    text-decoration: none;
    border-radius: 4px;
  }
  
  .add-employee-btn:hover {
    background-color: #0062cc;
  }

</style>
{% endblock %}

apps/dashboard/templates/Employee/employee_update.html
{% block content %}
  <div class="update-form-container">
    <h2>Update Employee "{{ employee.name }}"</h2>
    <form method="post" class="update-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="update-button">Update</button>
    </form>
  </div>
  <style>

  .update-form-container {
  margin: 20px;
  padding: 20px;
  background-color: #f2f2f2;
  border-radius: 5px;
}

.update-form {
  display: flex;
  flex-direction: column;
}

.update-button {
  background-color: #4CAF50;
  color: white;
  padding: 10px;
  border: none;
  border-radius: 5px;
  margin-top: 10px;
  cursor: pointer;
}

.update-button:hover {
  background-color: #3e8e41;
}
  </style>
{% endblock %}

apps/dashboard/templates/Order/ordercreate.html
{% block content %}
  <div class="container">
    <h2>Create a new order</h2>
    <form class="form" method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="button" type="submit">Create</button>
    </form>
  </div>
  
  <style>
    .container {
      width: 80%;
      margin: auto;
      padding: 20px;
      background-color: #7e67d8;
      border-radius: 10px;
    }
    
    h2 {
      font-size: 24px;
      text-align: center;
      margin-bottom: 20px;
    }
    
    .form {
      display: flex;
      flex-direction: column;
      align-items: center;
    }
    
    .form label {
      font-size: 16px;
      margin-bottom: 10px;
      text-align: left;
      width: 100%;
    }
    
    .form input[type="text"], .form select {
      width: 100%;
      padding: 10px;
      margin-bottom: 20px;
      border: none;
      border-radius: 5px;
      background-color: #f5f5f5;
    }
    
    .form select {
      height: 40px;
    }
    
    .button {
      background-color: #4CAF50;
      color: white;
      border: none;
      border-radius: 5px;
      padding: 10px;
      width: 10%;
      font-size: 16px;
      cursor: pointer;
      transition: all 0.3s ease;
    }
    
    .button:hover {
      background-color: #3e8e41;
    }
  </style>
{% endblock %}

apps/dashboard/templates/Order/orderdelete.html
{% block content %}
  <h2>Delete order "{{ order.product }}"</h2>
  <p>Are you sure you want to delete this order?</p>
  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'customer-list' %}">Cancel</a>
  </form>
{% endblock %}

apps/dashboard/templates/Order/orderdetail.html
{% block content %}
  <div class="order">
    <h1>{{ object.product }}</h1>
    <h2>Заказ от {{ object.date }}</h2>
    <p>Клиент: <a href="{{ object.customer.get_absolute_url }}">{{ object.customer }}</a></p>
    <p>Сотрудник: {{ object.employee }}</p>
    <p>Общая сумма: {{ order.product.price }}$</p>
  </div>
{% endblock %}

{% block styles %}
  <style>
    .order {
      border: 1px solid #ccc;
      border-radius: 5px;
      padding: 10px;
      margin: 10px;
      background-color: #f8f8f8;
    }

    .order h1 {
      font-size: 24px;
      margin-top: 0;
    }

    .order h2 {
      font-size: 18px;
      margin-top: 0;
    }

    .order p {
      font-size: 16px;
      margin: 5px 0;
    }

    .order a {
      color: #0066cc;
      text-decoration: none;
    }

    .order a:hover {
      text-decoration: underline;
    }
  </style>
{% endblock %}

apps/dashboard/templates/Order/orderlist.html
{% block content %}
  <h1>Orders</h1>
  <ul>
    {% for order in order_list %}
    <li><a href="{{ order.get_absolute_url }}">{{ order.product }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url  'order_create' %}"><button type="button">Добавить заказ</button></a>
{% endblock %}
</body>

<style>
  body {
    font-family: Arial, sans-serif;
    background-color: #f8f8f8;
  }

  h1 {
    font-size: 32px;
    margin-bottom: 20px;
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  li {
    margin-bottom: 10px;
  }

  a {
    text-decoration: none;
    color: #007bff;
  }

  button {
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    cursor: pointer;
  }

  button:hover {
    background-color: #0062cc;
  }
</style>
</head>

<body>

apps/dashboard/templates/Order/orderupdate.html
{% block content %}
  <div class="update-form-container">
    <h2>Update order "{{ order.product }}"</h2>
    <form method="post" class="update-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="update-button">Update</button>
    </form>
  </div>
  <style>

  .update-form-container {
  margin: 20px;
  padding: 20px;
  background-color: #f2f2f2;
  border-radius: 5px;
}

.update-form {
  display: flex;
  flex-direction: column;
}

.update-button {
  background-color: #4CAF50;
  color: white;
  padding: 10px;
  border: none;
  border-radius: 5px;
  margin-top: 10px;
  cursor: pointer;
}

.update-button:hover {
  background-color: #3e8e41;
}
  </style>
{% endblock %}

apps/dashboard/templates/base.html
<html>
<head>
    <title>Dashboard</title>
</head>
<body>
    <h1>Welcome to GlobalTech!</h1>
    <ul>
        <li><a href="{% url 'customer-list' %}">Customers</a></li>
        <li><a href="{% url 'employee_list' %}">Employees</a></li>
        <li><a href="{% url 'order_list' %}">Orders</a></li>
    </ul>
    
    <style>

    ul li a:hover {
        background-color: #333;
        color: #fff;
    }

    /* Add style to the header */
    header {
        background-color: #333;
        color: #fff;
        padding: 20px;
        text-align: center;
    }

         h1 {
        text-align: center;
        margin-top: 70px;
        font-size: 36px;
        color: #2368bc;
        text-shadow: 2px 2px #eeeeee;
        animation: fadeInUp 1s ease-out;
    }
    
    ul {
        list-style-type: none;
        margin: 50px auto;
        width: 400px;
        padding: 0;
        text-align: center;
        animation: fadeIn 1s ease-out;
    }
    
    li {
        display: inline-block;
        margin: 20px;
    }
    
    a {
        display: block;
        width: 150px;
        height: 50px;
        line-height: 50px;
        border-radius: 5px;
        background-color: #9561ee;
        color: #171515;
        text-decoration: none;
        font-size: 30px;
        text-align: center;
        transition: all 0.3s ease-in-out;
    }
    
    a:hover {
        background-color: #666666;
    }
    
    @keyframes fadeInUp {
        0% {
            opacity: 0;
            transform: translateY(50px);
        }
        100% {
            opacity: 1;
            transform: translateY(0);
        }
    }
    
    @keyframes fadeIn {
        0% {
            opacity: 0;
            transform: scale(0.8);
        }
        100% {
            opacity: 1;
            transform: scale(1);
        }
    }


    footer {
        background-color: #333;
        color: #fff;
        padding: 20px;
        text-align: center;
        position: fixed;
        bottom: 0;
        width: 100%;
    }
</style>
    
</html>

apps/dashboard/templates/customer/customer_create.html
{% block content %}
  <div class="container">
    <h2 class="text-center mb-4">Create a new customer</h2>
    <form method="post" class="col-md-6 mx-auto">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">Create</button>
    </form>
  </div>

  <style>
    
  form {
    border: 1px solid #11b76d;
    padding: 10px;
    border-radius: 5px;
    margin-top: 20px;
  }
  
  form button {
    margin-top: 20px;
  }
  
  form label {
    display: block;
    margin-bottom: 5px;
  }
  
  form input,
  form select {
    width: 100%;
    padding: 5px;
    border-radius: 3px;
    border: 1px solid #1599c9;
    box-sizing: border-box;
    margin-bottom: 10px;
  }
  
  form input[type="checkbox"] {
    display: inline-block;
    margin-right: 10px;
  }
  
  .form-group {
    margin-bottom: 20px;
  }
  
  .form-group label {
    font-weight: bold;
  }</style>
{% endblock %}

apps/dashboard/templates/customer/customer_delete.html
{% block content %}
  <div class="customer-delete">
    <h2 class="customer-delete__title">Delete customer "{{ customer.name }}"</h2>
    <p class="customer-delete__message">Are you sure you want to delete this customer?</p>
    <form class="customer-delete__form" method="post">
      {% csrf_token %}
      <button class="customer-delete__button" type="submit">Delete</button>
      <a class="customer-delete__cancel-link" href="{% url 'customer-list' %}">Cancel</a>
    </form>
  </div>
  <style>
  .customer-delete {
  margin-top: 30px;
  padding: 20px;
  border: 1px solid #80cd5c;
  border-radius: 5px;
  box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
}

.customer-delete__title {
  font-size: 24px;
  font-weight: bold;
  margin-bottom: 10px;
}

.customer-delete__message {
  font-size: 16px;
  margin-bottom: 20px;
}

.customer-delete__form {
  display: flex;
  justify-content: flex-end;
  align-items: center;
}

.customer-delete__button {
  background-color: #f44336;
  color: #fff;
  border: none;
  padding: 10px 20px;
  border-radius: 5px;
  cursor: pointer;
  margin-right: 10px;
}

.customer-delete__cancel-link {
  color: #f44336;
  text-decoration: none;
  font-size: 16px;
}
  </style>
{% endblock %}

apps/dashboard/templates/customer/customer_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ customer.name }}</title>
  <link rel="stylesheet" href="{% static 'css/customer.css' %}">
</head>
<body>
  <div class="container">
    <h1>{{ customer.name }}</h1>
    <h2>Заказы:</h2>
    <ul>
      {% for order in customer.order_set.all %}
        <li>{{ order.product }} ({{ order.employee }})</li>
      {% endfor %}
    </ul>
    <h2>Общая сумма заказов: {{ total }}$</h2>
  </div>
  <style>

  .container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  background-color: #6ac86d;
  font-family: Arial, sans-serif;
}

h1 {
  font-size: 36px;
  margin-bottom: 20px;
}

h2 {
  font-size: 24px;
  margin-bottom: 10px;
}

ul {
  list-style: none;
  margin: 0;
  padding: 0;
}

li {
  margin-bottom: 5px;
}

h2 + ul {
  margin-top: 5px;
}

h2 + ul + h2 {
  margin-top: 20px;
}

h2 + ul + h2 + h2 {
  margin-top: 5px;
}
  </style>
</body>
</html>

apps/dashboard/templates/customer/customer_update.html
{% block content %}
  <div class="update-form-container">
    <h2>Update customer "{{ customer.name }}"</h2>
    <form method="post" class="update-form">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="update-button">Update</button>
    </form>
  </div>
  <style>

  .update-form-container {
  margin: 20px;
  padding: 20px;
  background-color: #f2f2f2;
  border-radius: 5px;
}

.update-form {
  display: flex;
  flex-direction: column;
}

.update-button {
  background-color: #4CAF50;
  color: white;
  padding: 10px;
  border: none;
  border-radius: 5px;
  margin-top: 10px;
  cursor: pointer;
}

.update-button:hover {
  background-color: #3e8e41;
}
  </style>
{% endblock %}

apps/dashboard/templates/customer/list.html
{% block content %}
  <h1>Клиенты</h1>
  <ul>
    {% for customer in customer_list %}
    <li><a href="{{ customer.get_absolute_url }}">{{ customer.name }}</a></li>
    {% endfor %}
  </ul>
  <a href="{% url 'customer_create' %}"><button type="button">Добавить клиента</button></a>
{% endblock %}
</body>

<style>
  body {
    font-family: Arial, sans-serif;
    background-color: #f8f8f8;
  }

  h1 {
    font-size: 32px;
    margin-bottom: 20px;
  }

  ul {
    list-style: none;
    padding: 0;
    margin: 0;
  }

  li {
    margin-bottom: 10px;
  }

  a {
    text-decoration: none;
    color: #007bff;
  }

  button {
    background-color: #007bff;
    color: #fff;
    border: none;
    border-radius: 5px;
    padding: 10px 20px;
    cursor: pointer;
  }

  button:hover {
    background-color: #0062cc;
  }
</style>
</head>

<body>